# This file was generated by GoReleaser. DO NOT EDIT.
cask "forge" do
  desc "Easily run reusable steps from proprietary CI systems."
  homepage "https://github.com/frantjc/forge"
  version "1.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "forge"

  on_macos do
    on_intel do
      url "https://github.com/frantjc/forge/releases/download/v1.0.3/forge_1.0.3_darwin_amd64.tar.gz"
      sha256 "5c9cdf0adb8c2a87e35cab9284e274b4bb73b921835adec51cbf7fd4fb8c4f66"
    end
    on_arm do
      url "https://github.com/frantjc/forge/releases/download/v1.0.3/forge_1.0.3_darwin_arm64.tar.gz"
      sha256 "f61bafa1d285445f57f69dc153a73e4a617a73039e1e1a68ad5256a160f58dc6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/frantjc/forge/releases/download/v1.0.3/forge_1.0.3_linux_amd64.tar.gz"
      sha256 "8fef589c9abf92ea079ba99286525b2e94322c9dbbe52a1e7ae14f63002c6d92"
    end
    on_arm do
      url "https://github.com/frantjc/forge/releases/download/v1.0.3/forge_1.0.3_linux_arm64.tar.gz"
      sha256 "5d4a153e1eb0c84553affe05fbf90a150b3fc85761aec9074d3c123e22c92302"
    end
  end

  postflight do
    if OS.mac?
      if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/forge"]
      end
    end
  end

  # No zap stanza required
end
