# This file was generated by GoReleaser. DO NOT EDIT.
cask "forge" do
  desc "Easily run reusable steps from proprietary CI systems."
  homepage "https://github.com/frantjc/forge"
  version "1.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "forge"

  on_macos do
    on_intel do
      url "https://github.com/frantjc/forge/releases/download/v1.0.2/forge_1.0.2_darwin_amd64.tar.gz"
      sha256 "8f31ffa69eafa8c6e8c4e1c614d86a278ea203adbe239c00d10cbebd701dbf14"
    end
    on_arm do
      url "https://github.com/frantjc/forge/releases/download/v1.0.2/forge_1.0.2_darwin_arm64.tar.gz"
      sha256 "1eaeaadec2f6f48cd8bdb3f5797224a17de62e6fd8b234a3d98efc86852ca97f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/frantjc/forge/releases/download/v1.0.2/forge_1.0.2_linux_amd64.tar.gz"
      sha256 "52a1f992db2b980bec75c40232a09575990b988bc2b062c0ace588c2058befbc"
    end
    on_arm do
      url "https://github.com/frantjc/forge/releases/download/v1.0.2/forge_1.0.2_linux_arm64.tar.gz"
      sha256 "673ea964465ad34edaba1d3119a2a0e283eb6d9e5a9efa159640fcb3445427ce"
    end
  end

  conflicts_with formula: [
      "forge",
    ]

  postflight do
    if OS.mac?
      if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/forge"]
      end
    end
  end

  # No zap stanza required
end
