# This file was generated by GoReleaser. DO NOT EDIT.
cask "rvglsm" do
  desc "Track RVGL session scores."
  homepage "https://github.com/frantjc/rvgl-utils"
  version "0.4.2-alpha0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rvglsm"

  on_macos do
    on_intel do
      url "https://github.com/frantjc/rvgl-utils/releases/download/v0.4.2-alpha0/rvgl-utils_0.4.2-alpha0_darwin_amd64.tar.gz"
      sha256 "b922cae313bfb13bbda66af9054251329c7aab13eb23da9fd172b291bedec748"
    end
    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the rvglsm
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/frantjc/rvgl-utils/releases/download/v0.4.2-alpha0/rvgl-utils_0.4.2-alpha0_linux_amd64.tar.gz"
      sha256 "21cfcd20cbd614da5b80b182e12f6af58348db5329603395b6b3ef03ef68f610"
    end
  end

  conflicts_with formula: [
      "rvglsm",
    ]

  postflight do
    if OS.mac?
      if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rvglsm"]
      end
    end
  end

  # No zap stanza required
end
