# This file was generated by GoReleaser. DO NOT EDIT.
cask "rvglsm" do
  desc "Track RVGL session scores."
  homepage "https://github.com/frantjc/rvgl-utils"
  version "0.4.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rvglsm"

  on_macos do
    on_intel do
      url "https://github.com/frantjc/rvgl-utils/releases/download/v0.4.3/rvgl-utils_0.4.3_darwin_amd64.tar.gz"
      sha256 "b943cee20f6ae0eb5d75df00d49d766595eb9894aff9498d96901cb90318f735"
    end
    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the rvglsm
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/frantjc/rvgl-utils/releases/download/v0.4.3/rvgl-utils_0.4.3_linux_amd64.tar.gz"
      sha256 "6a918d0ce9a90fada0f024c240a2b3e39ce7302a812209d1662aedcf2a0c21c9"
    end
  end

  conflicts_with formula: [
      "rvglsm",
    ]

  postflight do
    if OS.mac?
      if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rvglsm"]
      end
    end
  end

  # No zap stanza required
end
