# This file was generated by GoReleaser. DO NOT EDIT.
cask "rvglsm" do
  desc ""
  homepage ""
  version "0.4.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rvglsm"

  on_macos do
    on_intel do
      url "https://github.com/frantjc/rvgl-utils/releases/download/v0.4.1/rvgl-utils_0.4.1_darwin_amd64.tar.gz"
      sha256 "5541d8817b9f3991508558970710b94dfd957a266c6afe1be4661b31f08c8fd4"
    end
    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the rvglsm
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/frantjc/rvgl-utils/releases/download/v0.4.1/rvgl-utils_0.4.1_linux_amd64.tar.gz"
      sha256 "c583b577089c695c57e741b5a5ed9974b70410d17f9470d4270778a57e4321f5"
    end
  end

  conflicts_with formula: [
      "rvglsm",
    ]

  postflight do
    if OS.mac?
      if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rvglsm"]
      end
    end
  end

  # No zap stanza required
end
