# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forge < Formula
  desc "Easily run reusable steps from proprietary CI systems"
  homepage "https://github.com/frantjc/forge"
  version "0.3.0"
  license "MIT"

  on_macos do
    url "https://github.com/frantjc/forge/releases/download/v0.3.0/forge_0.3.0_darwin_amd64.tar.gz"
    sha256 "bc334ff73f702936d522181f3bb5d8ce5f3e7e5b9654ad94d73976121cf64cb7"

    def install
      bin.install "forge"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Forge
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/frantjc/forge/releases/download/v0.3.0/forge_0.3.0_linux_amd64.tar.gz"
      sha256 "4c56ef2da466e5201d6cbc9be20553e3cfe6983223422f80aff2f201b5968536"

      def install
        bin.install "forge"
      end
    end
  end

  test do
    system "#{bin}/forge --version"
  end
end
