# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forge < Formula
  desc "Easily run reusable steps from proprietary CI systems"
  homepage "https://github.com/frantjc/forge"
  version "0.4.3"
  license "MIT"

  on_macos do
    url "https://github.com/frantjc/forge/releases/download/v0.4.3/forge_0.4.3_darwin_amd64.tar.gz"
    sha256 "bd17acdc3817eb1f8eeab9bb61a092f1e34c1846ec80996ff208b24e3cae8dbd"

    def install
      bin.install "forge"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Forge
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/frantjc/forge/releases/download/v0.4.3/forge_0.4.3_linux_amd64.tar.gz"
      sha256 "9cb7d5d60169122795b79820da940ffc0d13ad02ec3be726558a93796decdf80"

      def install
        bin.install "forge"
      end
    end
  end

  test do
    system "#{bin}/forge --version"
  end
end
