# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forge < Formula
  desc "Easily run reusable steps from proprietary CI systems."
  homepage "https://github.com/frantjc/forge"
  version "0.13.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/frantjc/forge/releases/download/v0.13.6/forge_0.13.6_darwin_arm64.tar.gz"
      sha256 "1819ff4019562278b13f3e6e934c25b3ed6f258033278921b483d5d92cafe470"

      def install
        bin.install "forge"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/frantjc/forge/releases/download/v0.13.6/forge_0.13.6_darwin_amd64.tar.gz"
      sha256 "d928743575c3a6ada3d5c40760d84e528afbf8a935cd48d864da7451b8d34638"

      def install
        bin.install "forge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/frantjc/forge/releases/download/v0.13.6/forge_0.13.6_linux_arm64.tar.gz"
      sha256 "e1892d3c41ddb1d44a5f2d17be48eeb4f22610537aeb70fb1a9ac8a09737b31d"

      def install
        bin.install "forge"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/frantjc/forge/releases/download/v0.13.6/forge_0.13.6_linux_amd64.tar.gz"
      sha256 "b607ee605e3756999a3ae80c34cd22973ede69d58214cdeba0d64c97a209acff"

      def install
        bin.install "forge"
      end
    end
  end

  test do
    system "#{bin}/forge --version"
  end
end
