# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kontrol < Formula
  desc "Package and deploy Kubernetes controllers"
  homepage "https://github.com/frantjc/kontrol"
  version "0.1.4"
  license "MIT"

  on_macos do
    url "https://github.com/frantjc/kontrol/releases/download/v0.1.4/kontrol_0.1.4_darwin_amd64.tar.gz"
    sha256 "4f45b8f4cb2de20f5d06faff21b7561c53c27850fe086cb234e7ee20915783bb"

    def install
      bin.install "kontrol"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Kontrol
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/frantjc/kontrol/releases/download/v0.1.4/kontrol_0.1.4_linux_amd64.tar.gz"
      sha256 "103ff41d75bb3eb30b1b75042fa08e961cb641343e3b04b230815d5749f51a16"

      def install
        bin.install "kontrol"
      end
    end
  end

  test do
    system "#{bin}/kontrol --version"
  end
end
