# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kontrol < Formula
  desc "Package and deploy Kubernetes controllers"
  homepage "https://github.com/frantjc/kontrol"
  version "0.1.5"
  license "MIT"

  on_macos do
    url "https://github.com/frantjc/kontrol/releases/download/v0.1.5/kontrol_0.1.5_darwin_amd64.tar.gz"
    sha256 "50ded38993c2671b5387546a7ef6cbff726dadf8fda42079574c610f34505848"

    def install
      bin.install "kontrol"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Kontrol
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/frantjc/kontrol/releases/download/v0.1.5/kontrol_0.1.5_linux_amd64.tar.gz"
      sha256 "0dd5f280badc6ff3d7bf8057f6856b2d0bf4023a5781f338776e2827411f9c8b"

      def install
        bin.install "kontrol"
      end
    end
  end

  test do
    system "#{bin}/kontrol --version"
  end
end
