# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kontrol < Formula
  desc "Package and deploy Kubernetes controllers"
  homepage "https://github.com/frantjc/kontrol"
  version "0.2.1"
  license "MIT"

  on_macos do
    url "https://github.com/frantjc/kontrol/releases/download/v0.2.1/kontrol_0.2.1_darwin_amd64.tar.gz"
    sha256 "0a233456f69ab1f803ad254135efacb5c25df426d04a7b6c3d9c011cf33a6d60"

    def install
      bin.install "kontrol"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Kontrol
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/frantjc/kontrol/releases/download/v0.2.1/kontrol_0.2.1_linux_amd64.tar.gz"
      sha256 "8be6289da6b4ab47ccb79f3b08a51a744887323f87ffb474abbf4d0cf83fd9ca"

      def install
        bin.install "kontrol"
      end
    end
  end

  test do
    system "#{bin}/kontrol --version"
  end
end
