# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RvglUtils < Formula
  desc ""
  homepage "https://github.com/frantjc/rvgl-utils"
  version "0.1.0"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
    url "https://github.com/frantjc/rvgl-utils/releases/download/v0.1.0/rvgl-utils_0.1.0_linux_amd64.tar.gz"
    sha256 "954e0969daf9368394835a0287a651174da0b017c574524f80a0c445520f0220"
    def install
      bin.install "rvglsm"
    end
  end

  test do
    system "#{bin}/rvglsm --version"
  end
end
