# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rvglsm < Formula
  desc ""
  homepage "https://github.com/frantjc/rvgl-utils"
  version "0.1.0"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
    url "https://github.com/frantjc/rvgl-utils/releases/download/v0.1.0/rvgl-utils_0.1.0_linux_amd64.tar.gz"
    sha256 "8398b036b093c283f160f26857283f5c0e1b3c73b9af8d27a33b122a5c73f064"
    def install
      bin.install "rvgl-utils"
    end
  end

  test do
    system "#{bin}/rvglsm --version"
  end
end
