# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RvglUtils < Formula
  desc ""
  homepage "https://github.com/frantjc/rvgl-utils"
  version "0.1.0"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
    url "https://github.com/frantjc/rvgl-utils/releases/download/v0.1.0/rvgl-utils_0.1.0_linux_amd64.tar.gz"
    sha256 "5d81d66764248181df56c6051736da93876999b71812e5d8636c30cc31d7edaf"
    def install
      bin.install "rvgl-utils"
    end
  end

  test do
    system "#{bin}/rvglsm --version"
  end
end
