# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rvglsm < Formula
  desc ""
  homepage "https://github.com/frantjc/rvgl-utils"
  version "0.2.0"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
    url "https://github.com/frantjc/rvgl-utils/releases/download/v0.2.0/rvglsm_0.2.0_linux_amd64"
    sha256 "7cf227b14fb44244bd5be9a33cc96dca09bbf38d34bb83d91143416ef0f522ab"
    def install
      bin.install "rvglsm"
    end
  end

  test do
    system "#{bin}/rvglsm --version"
  end
end
